Use functools.singledispatch on Python 3.4+
vfaronov/httpolice pull request #7
Opened 2019-02-23 10:43 UTC by jayvdb

singledispatch dependency is a backport of the Python 3.4+
implementation of PEP 443

Closes https://github.com/vfaronov/httpolice/issues/6

2019-02-24 13:10 UTC, vfaronov requested changes
Would you mind putting these imports into [`httpolice.util.moves`](https://github.com/vfaronov/httpolice/blob/master/httpolice/util/moves.py)? Although they are not strictly moves within the standard library, I think they’d be appropriate there.

2019-02-25 12:21 UTC, jayvdb commented
No worries .. sounds good.

2019-02-25 12:52 UTC, jayvdb commented
Done

2019-02-25 18:32 UTC, merged

2019-02-25 18:33 UTC, vfaronov commented
Great, thank you! I’ll release this to PyPI within the next few days.

2019-03-02 15:26 UTC, vfaronov commented
Actually, I’m dropping Python 2 support from the upcoming HTTPolice 0.8 altogether. Sorry for the hassle.